apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mdl-wrapper-data
spec:
  accessModes:
    - {{ .Values.wrapper.storage.accessMode }}
  storageClassName: {{ .Values.wrapper.storage.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.wrapper.storage.size }}
